---
title: "exploring measurement variables"
output:
  word_document: default
  html_document: default
date: "2022-08-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(tidyverse)
library(readxl)
library(extrafont)
library(flextable)
library(corrr)
library(ggcorrplot)
library(writexl)
library(ggrepel)
```
```{r table-function}
#times new roman tables
my_ft_theme <- function(ft, ...) {
  # Remove vertical cell padding
  ft <- padding(ft, padding.top = 0, padding.bottom = 0, part = "all")
  
  # Change font to TNR 11
  ft <- font(ft, fontname = "Times New Roman", part = "all")
  ft <- fontsize(ft, part = "all", size = 12)
  ft
}
```

```{r loading data}
headscan_full1<-read_excel("C:\\Users\\kayna\\Documents\\headscan_dissertation\\headscan_full1.xlsx")

headscan_num <- select_if(headscan_full1, is.numeric)
headscan_num <- subset(headscan_num, select= -age)

str(headscan_num)
```

```{r making and writing correlation_data set}
correlation_data_full <- correlate(headscan_num)

#write_xlsx(correlation_data_full, "C:\\Users\\19177\\OneDrive - Colostate\\Desktop\\Dissertation\\headscan_dissertation\\correlation_data_full.xlsx")


#correlation_data.xlxs was created one time and upper (duplicate) values were deleted in excel

```



```{r making-correlation-dataset-wide}


correlation_data_wide <- correlation_data_full %>% 
  column_to_rownames(var="term")

str(correlation_data_wide)
```


```{r correlation-plot, fig.height=8, fig.width=8}
correlation_data_round <- round(correlation_data_wide, digits=1)

ggcorrplot(correlation_data_round, hc.order=FALSE,
             type= "lower",
             lab= TRUE,
             lab_size= 3,
             method= "circle",
             colors = c("tomato2", "white", "springgreen3"))+
  theme_bw()+theme(text=element_text(family= "Times New Roman"))+
  theme(axis.text.x =  element_text(angle=90))+
  labs(title="Correlation of facial dimension measurement variables")             
```





```{r loading-correlation-data}
correlation_data<-read_excel("C:\\Users\\kayna\\Documents\\headscan_dissertation\\correlation_data.xlsx")
```


```{r making-dataset-long}
correlation_data <- pivot_longer(correlation_data, AA_C:TrTr_L, names_to = "second_measure", values_to = "correlation")

correlation_data <- correlation_data %>% 
  rename(first_measure = "term")

correlation_data$both_measures <- paste(correlation_data$first_measure, sep= " & ", correlation_data$second_measure)

str(correlation_data)


```
```{r reorganizing-dataset-for-table}
correlation_data1 <- correlation_data[-c(1,2)]

correlation_data1 <- correlation_data1[, c(2,1)]

correlation_data1$correlation <- round(correlation_data1$correlation, digits=4)

correlation_data1 <- na.omit(correlation_data1)
```



```{r all-correlations-table}
#Size 12 Table TNR
flextable(correlation_data1) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Correlations") %>% 
  set_header_labels(values = list(both_measures = "Correlated Measurements",
                                  correlation = "Correlation")) %>% 
  autofit()
```


```{r all-correlations-plot, fig.height=45, fig.width=5}
#correlation_data1 %>%
  #mutate(both_measures=fct_reorder(both_measures, correlation)) %>% 
  #ggplot(aes(x=correlation, y=both_measures))+
    #geom_bar(stat= "identity", color= "black", fill = "white")+
    #theme_bw()+theme(text=element_text(family= "Times New Roman"))+
    #theme(axis.text.x = element_text(angle = 90))+ 
    #labs(title="Correlations",
       #y="Correlated Measures Abbreviation (see Appendix B)",
       #x="Correlation value")
```



```{r making-high_cor-dataset}
high_cor <- filter(correlation_data1, correlation > 0.7)
str(high_cor)
```


```{r high_cor-table}
flextable(high_cor) %>%
  my_ft_theme()%>% 
  bold(part = "header") %>% 
  set_caption("Correlations over 0.7") %>% 
  set_header_labels(values = list(both_measures = "Correlated Measurements",
                                  correlation = "Correlation")) %>% 
  autofit()
```

```{r high-cor-plot, fig.width=5, fig.height=5}
high_cor %>%
  mutate(both_measures=fct_reorder(both_measures, correlation)) %>% 
  ggplot(aes(x=correlation, y=both_measures))+
    geom_bar(stat= "identity", color= "black", fill = "white")+
    theme_bw()+theme(text=element_text(family= "Times New Roman"))+
    #theme(axis.text.x = element_text(angle = 90))+ 
    labs(title="Correlations over 0.7",
       y="Correlated Measures Abbreviation (see Appendix B)",
       x="Correlation value")
```

```{r adding-coder-abcd}
#headscan_full1<-read_excel("C:\\Users\\19177\\OneDrive - Colostate\\Desktop\\Dissertation\\headscan_dissertation\\headscan_full1.xlsx")

coders <- headscan_full1[-c(2:28, 30:33)]

coders <- coders %>% 
  rename(coder_name = "coder")

coders <- coders %>% 
  mutate(coder= case_when(
    coder_name == "Isabel" ~ "Rater A",
    coder_name == "Kayna" ~ "Rater B",
    coder_name == "Chandler" ~ "Rater C",
    coder_name == "Jared" ~ "Rater D"
  ))

str(coders)
```



```{r collection-numbers-per-coder, fig.height=4, fig.width=8}
coders %>% 
  ggplot(aes(x=fct_infreq(coder), label=scales::percent(prop.table(stat(count)))))+
    geom_bar(stat="count", binwidth = 4, color= "black", fill = "white")+
    geom_text(stat="count",
              position= position_dodge(0.9),
              vjust = -0.5, 
              size = 3)+
    theme_bw()+theme(text=element_text(family= "Times New Roman"))+
    labs(title="3D Measurment Data Collection per Rater",
         y="# of Scans Digitized",
         x="Rater")
```


```{r loading-intraRR}
intraRR<-read_excel("C:\\Users\\kayna\\Documents\\headscan_dissertation\\intraRR_iccs.xlsx")
intraRR <- intraRR[-1]
str(intraRR)
```



```{r intraRR-iccs-wrapped-by-coder, fig.height=8, fig.width=6}
intraRR %>%
  mutate(measure=fct_reorder(measure, icc_value, .desc=TRUE)) %>% 
  ggplot(aes(x=icc_value, y=measure))+
    geom_bar(stat= "identity", color= "black", fill = "white")+
    theme_bw()+theme(text=element_text(family= "Times New Roman"))+
  facet_wrap(coder~.)+
    #theme(axis.text.x = element_text(angle = 90))+ 
    labs(title="IntraRR ICC Values",
         subtitle = "Percent of Data Collected per Coder: A=29%, B=43%, C=14%, D=14%",
         y="Measurement Location",
         x="ICC Value")
```

THIS IS WHERE I LEFT OFF NOTATIONS


```{r seperating-intra-into-coder}
isabel_intra <- intraRR[intraRR$coder=="A",]
kayna_intra <- intraRR[intraRR$coder == "B",]
chandler_intra <- intraRR[intraRR$coder == "C",]
jared_intra <- intraRR[intraRR$coder == "D",]

#write_xlsx(isabel_intra, "C:\\Users\\19177\\OneDrive - Colostate\\Desktop\\Dissertation\\headscan_dissertation\\isabel_intra.xlsx")
#write_xlsx(kayna_intra, "C:\\Users\\19177\\OneDrive - Colostate\\Desktop\\Dissertation\\headscan_dissertation\\kayna_intra.xlsx")
#write_xlsx(chandler_intra, "C:\\Users\\19177\\OneDrive - Colostate\\Desktop\\Dissertation\\headscan_dissertation\\chandler_intra.xlsx")
#write_xlsx(jared_intra, "C:\\Users\\19177\\OneDrive - Colostate\\Desktop\\Dissertation\\headscan_dissertation\\jared_intra.xlsx")
```


```{r isabel-plot, fig.height=6, fig.width=5}
isabel_intra %>%
  mutate(measure=fct_reorder(measure, icc_value, .desc=TRUE)) %>% 
  ggplot(aes(x=icc_value, y=measure))+
    geom_bar(stat= "identity", color= "black", fill = "white")+
    theme_bw()+theme(text=element_text(family= "Times New Roman"))+
    #theme(axis.text.x = element_text(angle = 90))+ 
    labs(title="Coder A ICC Values",
         subtitle = "completed 28.61% of data collection",
         y="Measurement Location",
         x="ICC Value")
```

```{r kayna-plot, fig.height=6, fig.width=5}
kayna_intra %>%
  mutate(measure=fct_reorder(measure, icc_value, .desc=TRUE)) %>% 
  ggplot(aes(x=icc_value, y=measure))+
    geom_bar(stat= "identity", color= "black", fill = "white")+
    theme_bw()+theme(text=element_text(family= "Times New Roman"))+
    #theme(axis.text.x = element_text(angle = 90))+ 
    labs(title="Coder B ICC Values",
         subtitle = "completed 42.98% of data collection",
         y="Measurement Location",
         x="ICC Value")
```

```{r chandler-plot, fig.height=6, fig.width=5}
chandler_intra %>%
  mutate(measure=fct_reorder(measure, icc_value, .desc=TRUE)) %>% 
  ggplot(aes(x=icc_value, y=measure))+
    geom_bar(stat= "identity", color= "black", fill = "white")+
    theme_bw()+theme(text=element_text(family= "Times New Roman"))+
    #theme(axis.text.x = element_text(angle = 90))+ 
    labs(title="Coder C ICC Values",
         subtitle = "completed 14.53% of data collection",
         y="Measurement Location",
         x="ICC Value")
```

```{r jared-plot, fig.height=6, fig.width=5}
jared_intra %>%
  mutate(measure=fct_reorder(measure, icc_value, .desc=TRUE)) %>% 
  ggplot(aes(x=icc_value, y=measure))+
    geom_bar(stat= "identity", color= "black", fill = "white")+
    theme_bw()+theme(text=element_text(family= "Times New Roman"))+
    #theme(axis.text.x = element_text(angle = 90))+ 
    labs(title="Coder D ICC Values",
         subtitle = "completed 13.88% of data collection",
         y="Measurement Location",
         x="ICC Value")
```




```{r making-low-intra-icc-dataset-adding-percent-column}
low_intraRR <- filter(intraRR, icc_value < 0.9)

low_intraRR <- low_intraRR %>% 
  mutate(percent_coded= case_when(
    coder == "A" ~ "28.61%",
    coder ==  "B" ~ "42.98%",
    coder ==  "C" ~ "14.53%",
    coder == "D" ~ "13.88%"
  ))

str(low_intraRR)
```

```{r low-intraRR-iccs-wrapped-by-coder, fig.height=8, fig.width=6}
low_intraRR %>%
  mutate(measure=fct_reorder(measure, icc_value, .desc=TRUE)) %>% 
  ggplot(aes(x=icc_value, y=measure))+
    geom_bar(stat= "identity", color= "black", fill = "white")+
    theme_bw()+theme(text=element_text(family= "Times New Roman"))+
  facet_wrap(coder~.)+
    #theme(axis.text.x = element_text(angle = 90))+ 
    labs(title="Low ICC Values",
         subtitle = "Percent of Data Collected per Coder: A=29%, B=43%, C=14%, D=14%",
         y="Measurement Location",
         x="ICC Value")
```

```{r stacked-intraRR-values-bar-plot}
low_intraRR %>% 
  ggplot(aes(x=measure, y=icc_value, fill=coder))+
  geom_bar(position = "dodge", stat = "identity")+
  theme_bw()+theme(text=element_text(family= "Times New Roman"))+
  theme(axis.text.x = element_text(angle = 90))+ 
  labs(title="Low ICC values for all Coders",
       subtitle = "Percent of Data Collected per Coder: A=29%, B=43%, C=14%, D=14%",
       y="ICC Value",
       x="Measurement Location")
```



```{r making-correlation-dataset-long}
correlation_datafl <- pivot_longer(correlation_data_full, AA_C:TrTr_L, names_to = "second_measure", values_to = "correlation")

correlation_datafl <- correlation_datafl %>% 
  rename(first_measure = "term")

correlation_datafl$both_measures <- paste(correlation_datafl$first_measure, sep= " & ", correlation_datafl$second_measure)

str(correlation_data)
```

```{r reorganizing-correlation-dataset-for-table}

correlation_datafl$correlation <- round(correlation_datafl$correlation, digits=4)

correlation_datafl <- na.omit(correlation_datafl)
```


```{r making-high-cor-dataset}
high_cor_full <- filter(correlation_datafl, correlation > 0.7)
high_cor_full <- high_cor_full %>% 
  rename(measure = "first_measure")
str(high_cor_full)
```



```{r joining-low-intra-and-high-cor-datasets}
#join lower intra and high cor full, retain lower intra dataset
questionable_measures <- full_join(low_intraRR, high_cor_full, by="measure")
questionable_measures <- questionable_measures %>% 
  rename(correlated_measure = "second_measure",
         intra_icc = "icc_value")

questionable_measures <- questionable_measures[, c(1,4,2,5,3,6,7)]

str(questionable_measures)
```

```{r renaming-flipped-factor-levels-both-measures}
questionable_measures$both_measures <-
  recode_factor(questionable_measures$both_measures, 'SmanM_C & SmanM_L' = "SmanM_L & SmanM_C",
                'BiW_C & BiW_L' = "BiW_L & BiW_C",
                'TrSnas_C & TrSel_C' = "TrSel_C & TrSnas_C",
                'ProA_L & AA_C' = "AA_C & ProA_L",
                'ProA_C & AA_C' = "AA_C & ProA_C",
                'TrSman_C & GoSub_C' = "GoSub_C & TrSman_C",
                'ProA_C & ProA_L' = "ProA_L & ProA_C",
                'ProS_C & ProS_L' = "ProS_L & ProS_C",
                'SelP_C & SelP_L' = "SelP_L & SelP_C",
                'SnasM_C & SelM_L' = "SelM_L & SnasM_C",
                'SnasM_C & SnasM_L' = "SnasM_L & SnasM_C",
                'TrSnas_C & TrSman_C' = "TrSman_C & TrSnas_C",
                'TrTr_C & TrTr_L' = "TrTr_L & TrTr_C",
                'TrSnas_C & TrTr_L' = "TrTr_L & TrSnas_C",
                'TrSel_C & TrTr_L' = "TrTr_L & TrSel_C",
                'SelM_L & SnasM_L' = "SnasM_L & SelM_L",
                'TrSnas_C & TrTr_C' = "TrTr_C & TrSnas_C",
                'TrSel_C & TrTr_C' = "TrTr_C & TrSel_C")

str(questionable_measures$both_measures)
```

```{r removing-na-values}
quest_meas_nona <- na.omit(questionable_measures)
```


```{r}
myFont1 <- "Times New Roman"
```


```{r intra-by cor-all-plot, fig.height=5, fig.width=8}
quest_meas_nona %>% 
  ggplot(aes(x=intra_icc, y=correlation))+
  geom_point(aes(shape=both_measures, color=coder), size=5)+
  geom_text_repel(aes(label=measure), family="Times New Roman", size= 2.5, color="gray50")+
  annotate(geom="text", x=0.4, y=0.84, label= "Highly correlated measures with low intraRR", 
           size=3.5, fontface = 'italic', family= myFont1, hjust=0, vjust=0)+
  scale_shape_manual(values=seq(0,12))+
  geom_rect(aes(xmin=0.4, xmax=0.75, ymin=0.85, ymax=1), fill= NA, alpha=0.4, colour="black")+
  theme_bw()+theme(text=element_text(family= "Times New Roman"))+
  #theme(axis.text.x = element_text(angle = 90))+ 
  labs(title="Correlation by IntraRR ICC values",
        subtitle = "Percent of Data Collected per Coder: A=29%, B=43%, C=14%, D=14%",
        y="Correlation",
        x="IntraRR ICC Value",
       shape="Correlated Measurements",
       color="Coder")
```

```{r intra-by-cor-wrapped plot, fig.height=5, fig.width=8.5}
quest_meas_nona %>% 
  ggplot(aes(x=intra_icc, y=correlation))+
  geom_point(aes(shape=both_measures, color=both_measures), size=5)+
   geom_text_repel(aes(label=measure), family="Times New Roman", size= 2.5, color="gray50")+
  annotate(geom="text", x=0.4, y=0.833, label= "Highly correlated measures with low intraRR", 
           size=2.5, fontface = 'italic', family= myFont1, hjust=0, vjust=0)+
  scale_shape_manual(values=seq(0,12))+
  geom_rect(aes(xmin=0.4, xmax=0.75, ymin=0.85, ymax=1), fill= NA, alpha=0.4, colour="black")+
  facet_wrap(coder~.)+
  theme_bw()+theme(text=element_text(family= "Times New Roman"))+
  #theme(axis.text.x = element_text(angle = 90))+ 
  labs(title="Correlation by IntraRR ICC values",
        subtitle = "Percent of Data Collected per Coder: A=29%, B=43%, C=14%, D=14%",
        y="Correlation",
        x="IntraRR ICC Value",
       shape="Correlated Measurements",
       color="Correlated Measurements")
```

```{r loading-inter-data-and-making-lowinter-dataset}
interRR<-read_excel("C:\\Users\\kayna\\Documents\\headscan_dissertation\\interRR_iccs.xlsx")
interRR <- interRR[-1]
interRR <- interRR %>% 
  rename(inter_icc = "icc_value")


#write_xlsx(interRR, "C:\\Users\\19177\\OneDrive - Colostate\\Desktop\\Dissertation\\headscan_dissertation\\interRR.xlsx")

low_interRR <- filter(interRR, inter_icc < 0.9)
```


```{r plotting-all-inter-iccs}
interRR %>%
  mutate(measure=fct_reorder(measure, inter_icc, .desc=TRUE)) %>% 
  ggplot(aes(x=inter_icc, y=measure))+
    geom_bar(stat= "identity", color= "black", fill = "white")+
    theme_bw()+theme(text=element_text(family= "Times New Roman"))+
    #theme(axis.text.x = element_text(angle = 90))+ 
    labs(title="InterRR Values",
         y="Measurement Location",
         x="ICC Value")
```
```{r plotting-low-inter-iccs}
low_interRR %>%
  mutate(measure=fct_reorder(measure, inter_icc, .desc=TRUE)) %>% 
  ggplot(aes(x=inter_icc, y=measure))+
    geom_bar(stat= "identity", color= "black", fill = "white")+
    theme_bw()+theme(text=element_text(family= "Times New Roman"))+
    #theme(axis.text.x = element_text(angle = 90))+ 
    labs(title="Low InterRR Values",
         y="Measurement Location",
         x="ICC Value")
```



```{r joining-inter-with-quesmeas-data}
questionable_measures <- full_join(questionable_measures, low_interRR, by = "measure")

questionable_measures <- questionable_measures[, c(1,2,3,4,5,8,6,7)]

str(questionable_measures)
```

```{r removing-na-values-from-inter-and-correlation}
quest_meas_nona1 <- questionable_measures %>%  
  drop_na(inter_icc) %>% 
  drop_na(correlation)
```


```{r inter-icc-by-correlation-plot, fig.height=5, fig.width=8}
quest_meas_nona1 %>% 
  ggplot(aes(x=inter_icc, y=correlation, na.rm=TRUE))+
  geom_point(aes(shape=both_measures, color=both_measures), size=5, na.rm = TRUE)+
  geom_text_repel(aes(label=measure), family="Times New Roman", size= 2.5, color="gray50")+
  annotate(geom="text", x=0.25, y=0.835, label= "Highly correlated measures with low interRR", 
           size=3.5, fontface = 'italic', family= myFont1, hjust=0, vjust=0)+
  scale_shape_manual(values=seq(0,12))+
  geom_rect(aes(xmin=0.25, xmax=0.75, ymin=0.845, ymax=1), fill= NA, alpha=0.4, colour="black")+
  xlim(0.25, 0.9)+
  theme_bw()+theme(text=element_text(family= "Times New Roman"))+
  #theme(axis.text.x = element_text(angle = 90))+ 
  labs(title="Correlation by InterRR ICC values",
        y="Correlation",
        x="InterRR ICC Value",
       shape="Correlated Measurements",
       color="Correlated Measurements")
```
```{r making-new-dataset-by-dropping-inter-and-intra-na-vals}
quest_meas_nona2 <- questionable_measures %>%  
  drop_na(inter_icc) %>% 
  drop_na(intra_icc)
```


```{r ploting-inter-by-intra,  fig.height=5, fig.width=8.5}
quest_meas_nona2 %>% 
  ggplot(aes(x=inter_icc, y=intra_icc, na.rm=TRUE))+
  geom_point(aes(shape=measure, color=measure), size=5, na.rm = TRUE)+
  #geom_text_repel(aes(label=measure), family="Times New Roman", size= 2.5, color="gray50")+
  annotate(geom="text", x=0.02, y=0.27, label= "Measurements w/ low intraRR and interRR", 
           size=2.5, fontface = 'italic', family= myFont1, hjust=0, vjust=0)+
  scale_shape_manual(values=seq(0,18))+
  geom_rect(aes(xmin=0, xmax=0.75, ymin=0.25, ymax=0.75), fill= NA, alpha=0.4, colour="black")+
  facet_wrap(coder~.)+
  theme_bw()+theme(text=element_text(family= "Times New Roman"))+
  #theme(axis.text.x = element_text(angle = 90))+ 
  labs(title="Correlation by InterRR ICC values",
       subtitle = "Percent of Data Collected per Coder: A=29%, B=43%, C=14%, D=14%",
        y="IntraRR ICC Value",
        x="InterRR ICC Value",
       shape="Measurement Location",
       color="Measurement Location")
```

```{r bar-plot-of-measure-names-that-are-questionable}
#it might be a good idea to show this plot several times and color code specific correlations as they are discussed
questionable_measures %>% 
  ggplot(aes(x=fct_infreq(measure), label=scales::percent(prop.table(stat(count)))))+
    geom_bar(stat="count", binwidth = 4, color= "black", fill = "white")+
    theme_bw()+theme(text=element_text(family= "Times New Roman"))+
    theme(axis.text.x = element_text(angle = 90))+
    labs(title="Questionable Stats per Measure",
         y="# of Questionable Stats",
         x="Measure Abbreviation")
```

```{r writing-questionable-measures}
#write_xlsx(questionable_measures, "C:\\Users\\19177\\OneDrive - Colostate\\Desktop\\Dissertation\\headscan_dissertation\\questionable_measures.xlsx")
```

