---
title: "PCA2"
output:
  word_document: default
  html_document: default
date: "2022-08-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(flextable)
library(readxl)
library(extrafont)
library(fauxnaif) #na if in
library(reshape2) #melt
library(FactoMineR) #PCA
library(kohonen)
library(adegenet)
```


```{r}
PCAdata_full<-read_excel("C:\\Users\\kayna\\Documents\\headscan_dissertation\\chosen_nona.xlsx")

str(PCAdata_full)
```


```{r}
#https://tem11010.github.io/Plotting-PCAs/

PCAdata_full1 <-  PCAdata_full %>% filter (AA_C > 0, BiW_C > 0, BiW_L > 0, GoSub_C > 0, 
                                           NRB_L > 0, ProS_L > 0, SelP_L > 0, SelM_L > 0, 
                                           SnasM_C > 0, TrSman_C > 0, TrTr_C > 0, TrTr_L > 0)

# log price

# center and scale the data
for (i in 1:length(colnames(PCAdata_full1))){
  
  if (is.numeric(PCAdata_full1[, i])==TRUE)
    
    PCAdata_full1[, i] <- as.numeric(scale(PCAdata_full1[, i]))
  
  else
    
    PCAdata_full1[, i] <- PCAdata_full1[, i]
  
}
```


```{r}
pca1 <- PCA(PCAdata_full1[ ,c("AA_C", "BiW_C", "BiW_L", "GoSub_C", "NRB_L", "ProS_L", "SelP_L", 
                             "SelM_L", "SnasM_C", "TrSman_C", "TrTr_C", "TrTr_L")])

summary(pca1)
                                    
```



```{r}
#loadingplot(pca1, show.names = TRUE)
```

```{r}
PCAdata_full1$pc1 <- pca1$ind$coord[, 1] # indexing the first column

PCAdata_full1$pc2 <- pca1$ind$coord[, 2]  # indexing the second column


```

```{r}
pca.vars <- pca1$var$coord %>% data.frame

pca.vars$vars <- rownames(pca.vars)

pca.vars.m <- melt(pca.vars, id.vars = "vars")
```

```{r}
#circleFun <- function(center = c(0,0),diameter = 1, npoints = 100){
  #r = diameter / 2
  #tt <- seq(0,2*pi,length.out = npoints)
  #xx <- center[1] + r * cos(tt)
  #yy <- center[2] + r * sin(tt)
  #return(data.frame(x = xx, y = yy))
#}

#circ <- circleFun(c(0,0),2,npoints = 500)
```





```{r, fig.width=8, fig.height=5}
ggplot(data = PCAdata_full1, aes(x = pc1, y = pc2)) +
  geom_point(color="darkgray")+
  labs(y="PC2 (19.51%)",
       x="PC1 (39.36%)",
       title="PCA plot")+
  theme_bw() + theme(text=element_text(family= "Times New Roman"))
```

```{r, fig.width=8, fig.height=5}
#checking to make sure this matches plot in PCA.Rmd
ggplot(data = PCAdata_full1, aes(x = pc1, y = pc2, color = race_eth)) +
      geom_hline(yintercept = 0, lty = 2) +
      geom_vline(xintercept = 0, lty = 2) +
      geom_point(alpha = 0.8) +
  labs(y="PC2 (19.51%)",
       x="PC1 (39.36%)",
       title = "All Race/Ethnicities PCA plot",
       color = "Race/Ethnicity")+
  theme_bw() + theme(text=element_text(family= "Times New Roman"))
```

```{r, fig.width=8, fig.height=5}
ggplot(data = PCAdata_full1, aes(x = pc1, y = pc2, color = race_eth)) +
      geom_hline(yintercept = 0, lty = 2) +
      geom_vline(xintercept = 0, lty = 2) +
      geom_point(alpha = 0.8) + 
  stat_ellipse(geom="polygon", aes(fill = race_eth), 
               alpha = 0.2, 
               show.legend = FALSE,
               level = 0.95) +
  #theme_minimal() +
  #theme(panel.grid = element_blank(), panel.border = element_rect(fill= "transparent"))+
  labs(y="PC2 (19.51%)",
       x="PC1 (39.36%)",
       title = "All Race/Ethnicities PCA plot",
       color = "Race/Ethnicity")+
  theme_bw() + theme(text=element_text(family= "Times New Roman"))
```
Need a plot with just Asian, Black, LatinX, and white

```{r}
PCAdata_full2 <- PCAdata_full1

PCAdata_full2$race_eth <- as.factor(PCAdata_full2$race_eth)
PCAdata_full2$gender <- as.factor(PCAdata_full2$gender)
PCAdata_full2$age_group <- as.factor(PCAdata_full2$age_group)
```

```{r}
PCAdata_race_eth <- PCAdata_full2

PCAdata_race_eth$race_eth <-  
  recode_factor(PCAdata_race_eth$race_eth, 'AIAN'= "Other",
                'NHOPI' = "Other",
                'PTNS' = "Other")

PCAdata_race_eth_nas <- PCAdata_full1 %>% 
  mutate(race_eth = na_if_in(race_eth, c("AIAN", "Other", "NHOPI", "PTNS")))

str(PCAdata_race_eth$race_eth)
str(PCAdata_race_eth_nas$race_eth)
```


```{r, fig.width=8, fig.height=5}
ggplot(data = PCAdata_race_eth, aes(x = pc1, y = pc2, color = race_eth)) +
      geom_hline(yintercept = 0, lty = 2) +
      geom_vline(xintercept = 0, lty = 2) +
      geom_point(alpha = 0.8) + 
  stat_ellipse(geom="polygon", aes(fill = race_eth), 
               alpha = 0.2, 
               show.legend = FALSE,
               level = 0.95) +
  #theme_minimal() +
  #theme(panel.grid = element_blank(), panel.border = element_rect(fill= "transparent"))+
  labs(y="PC2 (19.51%)",
       x="PC1 (39.36%)",
       title="Four Most Common Race/Ethnicities PCA plot",
       color = "Race/Ethnicity")+
  theme_bw() + theme(text=element_text(family= "Times New Roman"))
```


```{r, fig.width=8, fig.height=5}
PCAdata_race_eth_nas %>% 
  drop_na(race_eth) %>% 
  ggplot(aes(x = pc1, y = pc2, color = race_eth)) +
      geom_hline(yintercept = 0, lty = 2) +
      geom_vline(xintercept = 0, lty = 2) +
      geom_point(alpha = 0.8) + 
  stat_ellipse(geom="polygon", aes(fill = race_eth), 
               alpha = 0.2, 
               show.legend = FALSE,
               level = 0.95) +
  #theme_minimal() +
  #theme(panel.grid = element_blank(), panel.border = element_rect(fill= "transparent"))+
  labs(y="PC2 (19.51%)",
       x="PC1 (39.36%)",
       title="Race/Ethnicity PCA plot",
       subtitle="Other Race/Ethnicities not shown",
       color = "Race/Ethnicity")+
  theme_bw() + theme(text=element_text(family= "Times New Roman"))
```

Just Asian and Black?

```{r}
PCAdata_race_eth1 <- PCAdata_race_eth

PCAdata_race_eth1$race_eth <-
  recode_factor(PCAdata_race_eth1$race_eth, 'white'= "Other",
                'LatinX' = "Other")

PCAdata_race_eth_nas1 <- PCAdata_race_eth_nas %>% 
  mutate(race_eth = na_if_in(race_eth, c("white", "LatinX")))

str(PCAdata_race_eth1$race_eth)
str(PCAdata_race_eth_nas1$race_eth)
```

```{r, fig.width=8, fig.height=5}
ggplot(data = PCAdata_race_eth1, aes(x = pc1, y = pc2, color = race_eth)) +
      geom_hline(yintercept = 0, lty = 2) +
      geom_vline(xintercept = 0, lty = 2) +
      geom_point(alpha = 0.8) + 
  stat_ellipse(geom="polygon", aes(fill = race_eth, na.rm=TRUE), 
               alpha = 0.2, 
               show.legend = FALSE,
               level = 0.95) +
  #theme_minimal() +
  #theme(panel.grid = element_blank(), panel.border = element_rect(fill= "transparent"))+
  labs(y="PC2 (19.51%)",
       x="PC1 (39.36%)",
       title="Black and Asian Race/Ethnicities PCA plot",
       color = "Race/Ethnicity")+
  theme_bw() + theme(text=element_text(family= "Times New Roman"))
```

```{r, fig.width=8, fig.height=5}
PCAdata_race_eth_nas1 %>% 
  drop_na(race_eth) %>% 
  ggplot(aes(x = pc1, y = pc2, color = race_eth)) +
      geom_hline(yintercept = 0, lty = 2) +
      geom_vline(xintercept = 0, lty = 2) +
      geom_point(alpha = 0.8) + 
  stat_ellipse(geom="polygon", aes(fill = race_eth, na.rm=TRUE), 
               alpha = 0.2, 
               show.legend = FALSE,
               level = 0.95) +
  #theme_minimal() +
  #theme(panel.grid = element_blank(), panel.border = element_rect(fill= "transparent"))+
  labs(y="PC2 (19.51%)",
       x="PC1 (39.36%)",
       title="Black and Asian Race/Ethnicities PCA plot",
       subtitle = "Other Race/Ethnicities not shown",
       color = "Race/Ethnicity")+
  theme_bw() + theme(text=element_text(family= "Times New Roman"))
```

```{r, fig.width=8, fig.height=5}
#checking to make sure this matches plot in PCA.Rmd
ggplot(data = PCAdata_full1, aes(x = pc1, y = pc2, color = gender)) +
      geom_hline(yintercept = 0, lty = 2) +
      geom_vline(xintercept = 0, lty = 2) +
      geom_point(alpha = 0.8) +
  labs(y="PC2 (19.51%)",
       x="PC1 (39.36%)",
       title = "All Genders PCA plot",
       color= "Gender")+
  theme_bw() + theme(text=element_text(family= "Times New Roman"))
```


```{r, fig.width=8, fig.height=5}
ggplot(data = PCAdata_full1, aes(x = pc1, y = pc2, color = gender)) +
      geom_hline(yintercept = 0, lty = 2) +
      geom_vline(xintercept = 0, lty = 2) +
      geom_point(alpha = 0.8) + 
  stat_ellipse(geom="polygon", aes(fill = gender), 
               alpha = 0.2, 
               show.legend = FALSE,
               level = 0.95) +
  #theme_minimal() +
  #theme(panel.grid = element_blank(), panel.border = element_rect(fill= "transparent"))+
  labs(y="PC2 (19.51%)",
       x="PC1 (39.36%)",
       title="All Genders PCA plot",
       color= "Gender")+
  theme_bw() + theme(text=element_text(family= "Times New Roman"))
```
Need plot with just Male and Female 





```{r}
PCAdata_gender <- PCAdata_full2

PCAdata_gender$gender <-  
  recode_factor(PCAdata_gender$gender, 'Non-binary or Other'= "Other",
                'Prefer not to say' = "Other")

PCAdata_gender$gender[is.na(PCAdata_gender$gender)]="Other"

PCAdata_gender_nas <- PCAdata_full1 %>% 
  mutate(gender = na_if_in(gender, c("Non-binary or Other", "Prefer not to say", "Other")))

str(PCAdata_gender$gender)
str(PCAdata_gender_nas$gender)
```


```{r, fig.width=8, fig.height=5}
ggplot(data = PCAdata_gender, aes(x = pc1, y = pc2, color = gender)) +
      geom_hline(yintercept = 0, lty = 2) +
      geom_vline(xintercept = 0, lty = 2) +
      geom_point(alpha = 0.8) + 
  stat_ellipse(geom="polygon", aes(fill = gender), 
               alpha = 0.2, 
               show.legend = FALSE,
               level = 0.95) +
  #theme_minimal() +
  #theme(panel.grid = element_blank(), panel.border = element_rect(fill= "transparent"))+
  labs(y="PC2 (19.51%)",
       x="PC1 (39.36%)",
       title="Two Most Common Genders PCA plot",
       color = "Gender")+
  theme_bw() + theme(text=element_text(family= "Times New Roman"))
```


```{r}
PCAdata_gender1 <- PCAdata_gender

PCAdata_gender1$gender <-
  recode_factor(PCAdata_gender1$gender, 'Female'= "Female/Other",
                'Other' = "Female/Other")


ggplot(data = PCAdata_gender1, aes(x = pc1, y = pc2, color = gender)) +
      geom_hline(yintercept = 0, lty = 2) +
      geom_vline(xintercept = 0, lty = 2) +
      geom_point(alpha = 0.8) + 
  stat_ellipse(geom="polygon", aes(fill = gender), 
               alpha = 0.2, 
               show.legend = FALSE,
               level = 0.95) +
  #theme_minimal() +
  #theme(panel.grid = element_blank(), panel.border = element_rect(fill= "transparent"))+
  labs(y="PC2 (19.51%)",
       x="PC1 (39.36%)",
       title="Gender PCA Plot",
       color = "Gender")+
  theme_bw() + theme(text=element_text(family= "Times New Roman"))
```



```{r, fig.width=8, fig.height=5}
PCAdata_gender_nas %>% 
  drop_na(gender) %>% 
  ggplot(aes(x = pc1, y = pc2, color = gender)) +
      geom_hline(yintercept = 0, lty = 2) +
      geom_vline(xintercept = 0, lty = 2) +
      geom_point(alpha = 0.8) + 
  stat_ellipse(geom="polygon", aes(fill = gender), 
               alpha = 0.2, 
               show.legend = FALSE,
               level = 0.95) +
  #theme_minimal() +
  #theme(panel.grid = element_blank(), panel.border = element_rect(fill= "transparent"))+
  labs(y="PC2 (19.51%)",
       x="PC1 (39.36%)",
       title="Four Most Common Genders PCA plot",
       subtitle="Other Genders not shown",
       color = "Gender")+
  theme_bw() + theme(text=element_text(family= "Times New Roman"))
```



```{r, fig.width=8, fig.height=5}
#checking to make sure this matches plot in PCA.Rmd
ggplot(data = PCAdata_full1, aes(x = pc1, y = pc2, color = age_group)) +
      geom_hline(yintercept = 0, lty = 2) +
      geom_vline(xintercept = 0, lty = 2) +
      geom_point(alpha = 0.8) +
  labs(y="PC2 (19.51%)",
       x="PC1 (39.36%)",
       title = "Age Group PCA plot",
       color= "Age Group")+
  theme_bw() + theme(text=element_text(family= "Times New Roman"))
```


```{r, fig.width=8, fig.height=5}
ggplot(data = PCAdata_full1, aes(x = pc1, y = pc2, color = age_group)) +
      geom_hline(yintercept = 0, lty = 2) +
      geom_vline(xintercept = 0, lty = 2) +
      geom_point(alpha = 0.8) + 
  stat_ellipse(geom="polygon", aes(fill = age_group), 
               alpha = 0.2, 
               show.legend = FALSE,
               level = 0.95) +
  #theme_minimal() +
  #theme(panel.grid = element_blank(), panel.border = element_rect(fill= "transparent"))+
  labs(y="PC2 (19.51%)",
       x="PC1 (39.36%)",
       title = "All Age Groups PCA plot",
       color= "Age Group")+
  theme_bw() + theme(text=element_text(family= "Times New Roman"))
```



